language: cpp
sudo: required

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.9
          - libgmp-dev
          - libgmpxx4ldbl
          - libopenblas-dev
      before install:
      - git clone --depth 1 https://github.com/linbox-team/givaro.git && cd givaro && ./autogen.sh && make && sudo make install

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - libgmp-dev
          - libgmpxx4ldbl
          - libopenblas-dev
      before install:
      - git clone --depth 1 https://github.com/linbox-team/givaro.git && cd givaro && ./autogen.sh && make && sudo make install

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - libgmp-dev
          - libgmpxx4ldbl
          - libopenblas-dev
      before install:
      - git clone --depth 1 https://github.com/linbox-team/givaro.git && cd givaro && ./autogen.sh && make && sudo make install

    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   compiler: clang
    #   env: COMPILER=clang++
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       packages:
    #       - libgmp-dev
    #       - libgmpxx4ldbl
    #   before_install:
    #   - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
    #   - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    #   - sudo apt-get update -qq 
    #   - sudo apt-get install -qq -y clang-format-3.9

    - os: osx
      compiler: clang
      env: COMPILER=clang++
      before_install:
      - brew update
      - brew uninstall automake && brew install automake
      - brew install autoconf libtool
      - brew install libopenblas-dev
      - git clone --depth 1 https://github.com/linbox-team/givaro.git && cd givaro && ./autogen.sh && make && sudo make install

install:
  - export CXX="$COMPILER"

before_script:
  - ./autogen.sh

script:
  - make
  - make check
  - make benchmarks
  - make examples
  - make tutorials
  - make dist

notifications:
  on_success: change
  on_failure: always