VERSION=1.3.3

FFLAS_FFPACK_DIR=/usr/local/algebra/fflas-ffpack
LINBOX_DIR=/usr/local/algebra/linbox


dist:
	mkdir /tmp/fflas-ffpack-${VERSION}
	mkdir /tmp/fflas-ffpack-${VERSION}/tests /tmp/fflas-ffpack-${VERSION}/include /tmp/fflas-ffpack-${VERSION}/include/fflas-ffpack /tmp/fflas-ffpack-${VERSION}/benchmark /tmp/fflas-ffpack-${VERSION}/benchmark/graph /tmp/fflas-ffpack-${VERSION}/benchmark/html /tmp/fflas-ffpack-${VERSION}/benchmark/src /tmp/fflas-ffpack-${VERSION}/benchmark/test-src /tmp/fflas-ffpack-${VERSION}/benchmark/src/BLAS_LAPACK /tmp/fflas-ffpack-${VERSION}/benchmark/src/FFLAS_FFPACK /tmp/fflas-ffpack-${VERSION}/benchmark/src/BLOCKING
	cp ${FFLAS_FFPACK_DIR}/AUTHORS /tmp/fflas-ffpack-${VERSION}/
	cp ${FFLAS_FFPACK_DIR}/ChangeLog /tmp/fflas-ffpack-${VERSION}/
	cp ${FFLAS_FFPACK_DIR}/COPYING /tmp/fflas-ffpack-${VERSION}/
	cp ${FFLAS_FFPACK_DIR}/INSTALL /tmp/fflas-ffpack-${VERSION}/
	cp ${FFLAS_FFPACK_DIR}/README /tmp/fflas-ffpack-${VERSION}/
	cp ${FFLAS_FFPACK_DIR}/tests/timer.h ${FFLAS_FFPACK_DIR}/tests/timer.C ${FFLAS_FFPACK_DIR}/tests/Matio.h ${FFLAS_FFPACK_DIR}/tests/test-fgemm.C ${FFLAS_FFPACK_DIR}/tests/test-fgemv.C ${FFLAS_FFPACK_DIR}/tests/test-lqup.C ${FFLAS_FFPACK_DIR}/tests/test-charpoly.C ${FFLAS_FFPACK_DIR}/tests/test-compressQ.C ${FFLAS_FFPACK_DIR}/tests/test-frobenius.C ${FFLAS_FFPACK_DIR}/tests/test-fsquare.C ${FFLAS_FFPACK_DIR}/tests/test-det.C ${FFLAS_FFPACK_DIR}/tests/test-invert.C ${FFLAS_FFPACK_DIR}/tests/test-krylov-elim.C ${FFLAS_FFPACK_DIR}/tests/test-rank.C ${FFLAS_FFPACK_DIR}/tests/test-ftrsm.C ${FFLAS_FFPACK_DIR}/tests/testeur_fgemm.C ${FFLAS_FFPACK_DIR}/tests/testeur_lqup.C ${FFLAS_FFPACK_DIR}/tests/testeur_ftrsm.C ${FFLAS_FFPACK_DIR}/tests/dense_generator.C  /tmp/fflas-ffpack-${VERSION}/tests/
	cp ${FFLAS_FFPACK_DIR}/tests/Makefile.template /tmp/fflas-ffpack-${VERSION}/tests/Makefile
	cp ${FFLAS_FFPACK_DIR}/include/config-blas.h  /tmp/fflas-ffpack-${VERSION}/include
	cp ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fgemm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fgemv.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrmm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsv.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fdot.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_faxpy.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fcopy.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_bounds.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fger.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsm_src.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrmm_src.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kglu.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_danilevski.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kgfast.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kgfastgeneralized.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_frobenius.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_krylovelim.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_ludivine.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_minpoly.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/unparametric.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/modular-positive.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/modular-balanced.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/modular-int.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/modular-randiter.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/nonzero-randiter.h /tmp/fflas-ffpack-${VERSION}/include/fflas-ffpack

	cp ${FFLAS_FFPACK_DIR}/benchmark/run.sh /tmp/fflas-ffpack-${VERSION}/benchmark
	cp ${FFLAS_FFPACK_DIR}/benchmark/Makefile.Rule.template /tmp/fflas-ffpack-${VERSION}/benchmark/Makefile.Rule
	cp ${FFLAS_FFPACK_DIR}/benchmark/graph/graph_report.sh ${FFLAS_FFPACK_DIR}/benchmark/graph/make_graph_file.pl ${FFLAS_FFPACK_DIR}/benchmark/graph/make_graph.sh /tmp/fflas-ffpack-${VERSION}/benchmark/graph
	cp ${FFLAS_FFPACK_DIR}/benchmark/html/fflas.css ${FFLAS_FFPACK_DIR}/benchmark/html/html_report.sh ${FFLAS_FFPACK_DIR}/benchmark/html/html_report.xsl ${FFLAS_FFPACK_DIR}/benchmark/html/process.sh /tmp/fflas-ffpack-${VERSION}/benchmark/html
	cp ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/check-dgemm.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/check-dgetrf.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/check-dgetri.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/check-dtrsm.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/check-dtrtri.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLAS_LAPACK/Makefile /tmp/fflas-ffpack-${VERSION}/benchmark/src/BLAS_LAPACK
	cp ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/check-fgemm.C ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/check-ftrsm.C ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/check-ftrtri.C ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/check-inverse.C ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/check-lqup.C ${FFLAS_FFPACK_DIR}/benchmark/src/FFLAS_FFPACK/Makefile /tmp/fflas-ffpack-${VERSION}/benchmark/src/FFLAS_FFPACK
	cp ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/gnucommand ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/Makefile ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/mesure.sh ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/mulMM.C ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/plot1-mulMM ${FFLAS_FFPACK_DIR}/benchmark/src/BLOCKING/tblockmat.C /tmp/fflas-ffpack-${VERSION}/benchmark/src/BLOCKING
	cp ${FFLAS_FFPACK_DIR}/benchmark/test-src/mesure-BLAS_LAPACK.sh ${FFLAS_FFPACK_DIR}/benchmark/test-src/mesure-FFLAS_FFPACK.sh ${FFLAS_FFPACK_DIR}/benchmark/test-src/mesure.sh ${FFLAS_FFPACK_DIR}/benchmark/test-src/parameter.in /tmp/fflas-ffpack-${VERSION}/benchmark/test-src

	tar zcvf fflas-ffpack-${VERSION}.tar.gz  -C /tmp fflas-ffpack-${VERSION}
	rm -rf /tmp/fflas-ffpack-${VERSION}

linbox:
	cp ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fgemm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fgemv.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsv.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrmm.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fdot.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fcopy.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_faxpy.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_fger.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_bounds.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrsm_src.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/fflas_ftrmm_src.inl ${LINBOX_DIR}/linbox/fflas/
	cp ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack.h ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_frobenius.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_ludivine.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_minpoly.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_krylovelim.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_danilevski.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kglu.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kgfast.inl ${FFLAS_FFPACK_DIR}/include/fflas-ffpack/ffpack_charpoly_kgfastgeneralized.inl ${LINBOX_DIR}/linbox/ffpack/

