#----------------------------------------------------------
# Parameters to be configured by the user

# root for the blas library, for ex. /home/foo/ATLAS/lib/Linux_P4SSE2
BLASROOT = 

# ATLAS BLAS users : uncomment these lines:
#CXXFLAGS+=-D__LINBOX_HAVE_CBLAS
#LOADLIBES+=-L${BLASROOT} -lcblas -latlas

# GotoBlas BLAS users : uncomment this line:
#LOADLIBES+=-L${BLASROOT} -lgoto

# Other BLAS users, uncomment this line:
#LOADLIBES+=-L${BLASROOT} -lcblas

# architecture parameter for gcc: 
#ARCH = -march=pentium3 
#ARCH = -march=pentium4
#ARCH = -march=athlon
#ARCH = -march=opteron 
#ARCH = -m64 -mtune=k8

#----------------------------------------------------------

OPTFLAGS+=-O3
#OPTFLAGS+=-g
OPTFLAGS+= ${ARCH}

CXXFLAGS+=${OPTFLAGS} 

INCLUDES+=-I. -I../include 


CXX=g++ ${INCLUDES}

all: test-fgemm test-invert test-det test-rank test-charpoly test-lqup dense_generator

clean:
	rm -f test-fgemm test-fgemv test-invert test-det test-rank test-charpoly test-lqup dense_generator
